In [83]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import seaborn as sns
import matplotlib.pyplot as plt
import optuna
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score
import sklearn
import random


In [84]:
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import mean_absolute_error

In [85]:
filename = 'Dataset/Sensor_Discrimination_normalized.csv'
df=pd.read_csv(filename)
# shuffle the DataFrame rows
df = df.sample(frac = 1) #frac = fraction
dataset=df.iloc[:,:-1]
label=df.iloc[:,-1]
print(dataset)
print(label)

            F2        F3        F1       F11        F4        F6       F10  \
1072  0.117754  0.987046  0.968658  0.970922  0.989855  0.870808  0.952372   
2092  0.148321  0.904441  0.851518  0.245922  0.840013  0.551952  0.445218   
930   0.220963  0.963829  0.949070  0.296986  0.969400  0.674546  0.947854   
1252  0.991658  0.947847  0.870911  0.207624  0.828538  0.404893  0.534827   
1756  0.820321  0.572174  0.359647  0.213830  0.498586 -0.008725  0.269578   
...        ...       ...       ...       ...       ...       ...       ...   
245   0.137861  0.937584  0.916748  0.984929  0.985864  0.734195  0.971197   
404   0.708235  0.506561  0.260921  0.196454  0.351572  0.021811  0.202372   
1629  0.441711  0.566790  0.365132  0.189007  0.497755  0.039252  0.204443   
329   0.837219  0.730821  0.442116  0.176188  0.466323  0.113744  0.189194   
1839  0.418824  0.902254  0.602742  0.190248  0.682521  0.217757  0.284450   

            F9        F5      F7      F12      F8  
1072  0.758

# RFE implement

In [86]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR


estimator = SVR(kernel="linear")
model = RFE(estimator, n_features_to_select=3, step=1)
model.fit(dataset,label)



RFE(estimator=SVR(kernel='linear'), n_features_to_select=3)

In [87]:

compressed_dataset_X= model.transform(dataset) # --transform-- the original "dataset" Dataframe into a lower-dimensional space based on the model's learned parameters
print(type(compressed_dataset_X))
print(len(compressed_dataset_X[0]))
print(compressed_dataset_X)

<class 'numpy.ndarray'>
3
[[0.96865818 0.97092199 0.77995643]
 [0.85151812 0.24592199 0.22607117]
 [0.94906954 0.29698582 0.78467683]
 ...
 [0.36513222 0.18900709 0.14716776]
 [0.44211557 0.17618794 0.08376906]
 [0.60274241 0.19024823 0.19015977]]


In [88]:
dataset_arr=dataset.to_numpy()


In [89]:
# from NecessaryModules.splitData import split_data
X_train,X_comb, y_train,y_comb = train_test_split(dataset_arr, label, test_size=0.4, random_state=42)
print(len(X_train))

1327


In [90]:
X_valid, X_test, y_valid, y_test = train_test_split(X_comb, y_comb, test_size=0.50, random_state=42)
print(len(X_valid))

442


In [91]:
compressed_dataset_X_train= model.transform(X_train) # --transform-- the original "dataset" Dataframe into a lower-dimensional space based on the model's learned parameters
print(type(compressed_dataset_X_train))
print(len(compressed_dataset_X_train))
print(compressed_dataset_X_train)

compressed_dataset_X_valid= model.transform(X_valid) # --transform-- the original "dataset" Dataframe into a lower-dimensional space based on the model's learned parameters
print(type(compressed_dataset_X_valid))
print(len(compressed_dataset_X_valid))
print(compressed_dataset_X_valid)

compressed_dataset_X_test= model.transform(X_test) # --transform-- the original "dataset" Dataframe into a lower-dimensional space based on the model's learned parameters
print(type(compressed_dataset_X_test))
print(len(compressed_dataset_X_test))
print(compressed_dataset_X_test)

<class 'numpy.ndarray'>
1327
[[0.67247796 0.2322695  0.14673203]
 [0.7337904  0.2        0.21187364]
 [0.37590597 0.19680851 0.1325345 ]
 ...
 [0.31616063 0.1856383  0.13431373]
 [0.74338883 0.20886525 0.21053014]
 [0.9424094  0.95407801 0.88198983]]
<class 'numpy.ndarray'>
442
[[0.95259549 0.31968085 0.7476398 ]
 [0.89422135 0.27570922 0.65722585]
 [0.88227228 0.30531915 0.40740741]
 ...
 [0.25857003 0.1670922  0.0939724 ]
 [0.32184133 0.17315603 0.09219317]
 [0.87952987 0.25035461 0.36034858]]
<class 'numpy.ndarray'>
443
[[0.88912831 0.98687943 0.81953522]
 [0.90009794 0.41897163 0.81336238]
 [0.37610186 0.21843972 0.11481481]
 ...
 [0.96219393 0.30496454 0.82933914]
 [0.87522037 0.2891844  0.39288308]
 [0.87855044 0.96471631 0.83079158]]


# reshape the data 

In [92]:
compressed_dataset_X_valid.shape

(442, 3)

In [93]:
X_train_arr=compressed_dataset_X_train.reshape(compressed_dataset_X_train.shape[0],compressed_dataset_X_train.shape[1],1)
X_train_arr.shape

(1327, 3, 1)

In [94]:
# X_valid_arr=compressed_dataset_X_valid.to_numpy()
X_valid_arr=compressed_dataset_X_valid.reshape(compressed_dataset_X_valid.shape[0],compressed_dataset_X_valid.shape[1],1)
X_valid_arr.shape

(442, 3, 1)

In [95]:
X_test_arr=compressed_dataset_X_test.reshape(compressed_dataset_X_test.shape[0],compressed_dataset_X_test.shape[1],1)
X_test_arr.shape

(443, 3, 1)

In [96]:
# for "y"

y_train_arr=np.array(y_train)
y_train_arr=y_train_arr.reshape(y_train_arr.shape[0],1)

y_valid_arr=np.array(y_valid)
y_valid_arr=y_valid_arr.reshape(y_valid_arr.shape[0],1)

y_test_arr=np.array(y_test)
y_test_arr=y_test_arr.reshape(y_test_arr.shape[0],1)

In [97]:
y_test_arr.shape

(443, 1)

# one hot encode

In [98]:
from keras.utils import to_categorical
# one hot encoding
y_train_arr = to_categorical(y_train, 3)
y_valid_arr = to_categorical(y_valid, 3)
y_test_arr = to_categorical(y_test, 3)

In [99]:
y_test_arr

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]], dtype=float32)

# model

In [100]:

# cnn model
from numpy import mean
from numpy import std
from numpy import dstack
from pandas import read_csv
from matplotlib import pyplot
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Dropout
from keras.layers import Conv1D
from keras.layers import MaxPooling1D


In [101]:
import tensorflow as tf
callback=tf.keras.callbacks.EarlyStopping(
    monitor='val_loss',
    min_delta=0,
    patience=7,
    verbose=0,
    mode='auto',
    baseline=None,
    restore_best_weights=True,
    start_from_epoch=0
)

In [102]:
# Global value
verbose, epochs, batch_size = 1, 100, 50


In [106]:
# fit and evaluate a model
import optuna
from matplotlib import pyplot as plt

def optimize_model(trainX, trainy,validX,validy):
    n_timesteps, n_features, n_outputs = trainX.shape[1], trainX.shape[2], 3
    def objective_model1(trial):
    # Define hyperparameters to be tuned
     
     filters = trial.suggest_int('filters', 32, 64)
     kernel_size = 2
     dropout_rate = trial.suggest_float('dropout_rate', 0.1, 0.5)
     dense_units = trial.suggest_int('dense_units', 50, 200)
     
     # Build the CNN model
     model = Sequential()
     model.add(Conv1D(filters=filters, kernel_size=kernel_size, activation='relu', input_shape=(n_timesteps, n_features)))
     model.add(Conv1D(filters=filters, kernel_size=kernel_size-1, activation='relu'))
     model.add(Dropout(dropout_rate))
    #  model.add(MaxPooling1D(pool_size=2))
     model.add(Flatten())
     model.add(Dense(dense_units, activation='relu'))
     model.add(Dense(n_outputs, activation='softmax'))
 
     # Compile the model
     model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
 
     # Fit the model
     history = model.fit(trainX, trainy, validation_data=(validX, validy), epochs=epochs,callbacks=[callback],batch_size=batch_size, verbose=verbose)
    
    # Return the validation accuracy as the objective value
     return history.history['val_accuracy'][-1]
    study = optuna.create_study(direction='maximize')
    study.optimize(objective_model1, n_trials= 8, 
                   #timeout=600
                   )#The maximum time (in seconds) allowed for the optimization process to run.
    # Get the best hyperparameters
    best_params = study.best_params
    print("Best Hyperparameters:", best_params)


    return best_params
 



In [107]:
# summarize scores
def summarize_results(scores):
 print(scores)
 m, s = mean(scores), std(scores)
 print('Test Accuracy: %.3f%% (+/-%.3f)' % (m, s))
 

# Calculate the accuracy

In [108]:

best_params=optimize_model(X_train_arr, y_train_arr, X_valid_arr, y_valid_arr)

[I 2024-02-12 10:31:32,174] A new study created in memory with name: no-name-94d61fba-7125-4738-a6bc-926ca2dd95a0


Epoch 1/100
27/27 [==============================] - 1s 10ms/step - loss: 1.0587 - accuracy: 0.4928 - val_loss: 0.9804 - val_accuracy: 0.6109
Epoch 2/100
27/27 [==============================] - 0s 9ms/step - loss: 0.9308 - accuracy: 0.6940 - val_loss: 0.7565 - val_accuracy: 0.8281
Epoch 3/100
27/27 [==============================] - 0s 6ms/step - loss: 0.7353 - accuracy: 0.7807 - val_loss: 0.5801 - val_accuracy: 0.8394
Epoch 4/100
27/27 [==============================] - 0s 4ms/step - loss: 0.6381 - accuracy: 0.7867 - val_loss: 0.5011 - val_accuracy: 0.8484
Epoch 5/100
27/27 [==============================] - 0s 4ms/step - loss: 0.5649 - accuracy: 0.8048 - val_loss: 0.4713 - val_accuracy: 0.8394
Epoch 6/100
27/27 [==============================] - 0s 4ms/step - loss: 0.5464 - accuracy: 0.8093 - val_loss: 0.4694 - val_accuracy: 0.8303
Epoch 7/100
27/27 [==============================] - 0s 5ms/step - loss: 0.5176 - accuracy: 0.8191 - val_loss: 0.4416 - val_accuracy: 0.8303
Epoch 8/100


[I 2024-02-12 10:31:44,426] Trial 0 finished with value: 0.8800904750823975 and parameters: {'filters': 57, 'dropout_rate': 0.46611507569065225, 'dense_units': 120}. Best is trial 0 with value: 0.8800904750823975.


Epoch 1/100
27/27 [==============================] - 1s 10ms/step - loss: 1.0494 - accuracy: 0.4763 - val_loss: 0.9510 - val_accuracy: 0.7534
Epoch 2/100
27/27 [==============================] - 0s 5ms/step - loss: 0.8799 - accuracy: 0.7468 - val_loss: 0.6930 - val_accuracy: 0.8439
Epoch 3/100
27/27 [==============================] - 0s 5ms/step - loss: 0.6601 - accuracy: 0.7943 - val_loss: 0.5080 - val_accuracy: 0.8529
Epoch 4/100
27/27 [==============================] - 0s 4ms/step - loss: 0.5627 - accuracy: 0.8131 - val_loss: 0.4697 - val_accuracy: 0.8507
Epoch 5/100
27/27 [==============================] - 0s 4ms/step - loss: 0.5350 - accuracy: 0.8056 - val_loss: 0.4511 - val_accuracy: 0.8529
Epoch 6/100
27/27 [==============================] - 0s 5ms/step - loss: 0.5033 - accuracy: 0.8282 - val_loss: 0.4512 - val_accuracy: 0.8439
Epoch 7/100
27/27 [==============================] - 0s 5ms/step - loss: 0.4810 - accuracy: 0.8237 - val_loss: 0.4255 - val_accuracy: 0.8484
Epoch 8/100


[I 2024-02-12 10:31:55,970] Trial 1 finished with value: 0.9027149081230164 and parameters: {'filters': 52, 'dropout_rate': 0.237586017646276, 'dense_units': 191}. Best is trial 1 with value: 0.9027149081230164.


Epoch 1/100
27/27 [==============================] - 1s 11ms/step - loss: 1.0414 - accuracy: 0.5592 - val_loss: 0.9295 - val_accuracy: 0.7579
Epoch 2/100
27/27 [==============================] - 0s 4ms/step - loss: 0.8569 - accuracy: 0.7483 - val_loss: 0.6645 - val_accuracy: 0.8348
Epoch 3/100
27/27 [==============================] - 0s 5ms/step - loss: 0.6529 - accuracy: 0.7950 - val_loss: 0.5069 - val_accuracy: 0.8575
Epoch 4/100
27/27 [==============================] - 0s 4ms/step - loss: 0.5550 - accuracy: 0.8063 - val_loss: 0.4646 - val_accuracy: 0.8507
Epoch 5/100
27/27 [==============================] - 0s 4ms/step - loss: 0.5125 - accuracy: 0.8161 - val_loss: 0.4415 - val_accuracy: 0.8575
Epoch 6/100
27/27 [==============================] - 0s 5ms/step - loss: 0.4813 - accuracy: 0.8365 - val_loss: 0.4226 - val_accuracy: 0.8575
Epoch 7/100
27/27 [==============================] - 0s 5ms/step - loss: 0.4590 - accuracy: 0.8433 - val_loss: 0.4166 - val_accuracy: 0.8552
Epoch 8/100


[I 2024-02-12 10:32:05,927] Trial 2 finished with value: 0.8800904750823975 and parameters: {'filters': 52, 'dropout_rate': 0.23251617673502195, 'dense_units': 197}. Best is trial 1 with value: 0.9027149081230164.


Epoch 1/100
27/27 [==============================] - 1s 10ms/step - loss: 1.0509 - accuracy: 0.4521 - val_loss: 0.9670 - val_accuracy: 0.7195
Epoch 2/100
27/27 [==============================] - 0s 4ms/step - loss: 0.9297 - accuracy: 0.6903 - val_loss: 0.7972 - val_accuracy: 0.8394
Epoch 3/100
27/27 [==============================] - 0s 4ms/step - loss: 0.7621 - accuracy: 0.7845 - val_loss: 0.6133 - val_accuracy: 0.8462
Epoch 4/100
27/27 [==============================] - 0s 4ms/step - loss: 0.6369 - accuracy: 0.7965 - val_loss: 0.5203 - val_accuracy: 0.8507
Epoch 5/100
27/27 [==============================] - 0s 4ms/step - loss: 0.5757 - accuracy: 0.8101 - val_loss: 0.4862 - val_accuracy: 0.8507
Epoch 6/100
27/27 [==============================] - 0s 4ms/step - loss: 0.5397 - accuracy: 0.8116 - val_loss: 0.4616 - val_accuracy: 0.8552
Epoch 7/100
27/27 [==============================] - 0s 4ms/step - loss: 0.5128 - accuracy: 0.8206 - val_loss: 0.4568 - val_accuracy: 0.8371
Epoch 8/100


[I 2024-02-12 10:32:14,883] Trial 3 finished with value: 0.8868778347969055 and parameters: {'filters': 35, 'dropout_rate': 0.1613127789779003, 'dense_units': 170}. Best is trial 1 with value: 0.9027149081230164.


Epoch 1/100
27/27 [==============================] - 1s 10ms/step - loss: 1.0614 - accuracy: 0.5057 - val_loss: 0.9822 - val_accuracy: 0.6923
Epoch 2/100
27/27 [==============================] - 0s 4ms/step - loss: 0.9334 - accuracy: 0.6827 - val_loss: 0.7822 - val_accuracy: 0.8258
Epoch 3/100
27/27 [==============================] - 0s 4ms/step - loss: 0.7508 - accuracy: 0.7551 - val_loss: 0.5930 - val_accuracy: 0.8439
Epoch 4/100
27/27 [==============================] - 0s 4ms/step - loss: 0.6215 - accuracy: 0.7890 - val_loss: 0.5023 - val_accuracy: 0.8507
Epoch 5/100
27/27 [==============================] - 0s 4ms/step - loss: 0.5531 - accuracy: 0.8124 - val_loss: 0.4782 - val_accuracy: 0.8416
Epoch 6/100
27/27 [==============================] - 0s 4ms/step - loss: 0.5287 - accuracy: 0.8041 - val_loss: 0.5238 - val_accuracy: 0.7919
Epoch 7/100
27/27 [==============================] - 0s 4ms/step - loss: 0.5201 - accuracy: 0.8003 - val_loss: 0.4385 - val_accuracy: 0.8507
Epoch 8/100


[I 2024-02-12 10:32:26,430] Trial 4 finished with value: 0.8755655884742737 and parameters: {'filters': 62, 'dropout_rate': 0.2380423500046802, 'dense_units': 93}. Best is trial 1 with value: 0.9027149081230164.


Epoch 1/100
27/27 [==============================] - 1s 13ms/step - loss: 1.0298 - accuracy: 0.6232 - val_loss: 0.9072 - val_accuracy: 0.7511
Epoch 2/100
27/27 [==============================] - 0s 4ms/step - loss: 0.8497 - accuracy: 0.7084 - val_loss: 0.6730 - val_accuracy: 0.8281
Epoch 3/100
27/27 [==============================] - 0s 4ms/step - loss: 0.6871 - accuracy: 0.7687 - val_loss: 0.5402 - val_accuracy: 0.8620
Epoch 4/100
27/27 [==============================] - 0s 4ms/step - loss: 0.5979 - accuracy: 0.7988 - val_loss: 0.4841 - val_accuracy: 0.8484
Epoch 5/100
27/27 [==============================] - 0s 4ms/step - loss: 0.5500 - accuracy: 0.8184 - val_loss: 0.4543 - val_accuracy: 0.8529
Epoch 6/100
27/27 [==============================] - 0s 3ms/step - loss: 0.5047 - accuracy: 0.8372 - val_loss: 0.4310 - val_accuracy: 0.8462
Epoch 7/100
27/27 [==============================] - 0s 3ms/step - loss: 0.4993 - accuracy: 0.8086 - val_loss: 0.4225 - val_accuracy: 0.8529
Epoch 8/100


[I 2024-02-12 10:32:33,789] Trial 5 finished with value: 0.877828061580658 and parameters: {'filters': 38, 'dropout_rate': 0.27087644562896795, 'dense_units': 172}. Best is trial 1 with value: 0.9027149081230164.


Epoch 1/100
27/27 [==============================] - 1s 10ms/step - loss: 1.0704 - accuracy: 0.4310 - val_loss: 1.0039 - val_accuracy: 0.5158
Epoch 2/100
27/27 [==============================] - 0s 3ms/step - loss: 0.9863 - accuracy: 0.6089 - val_loss: 0.8773 - val_accuracy: 0.8348
Epoch 3/100
27/27 [==============================] - 0s 4ms/step - loss: 0.8351 - accuracy: 0.7061 - val_loss: 0.6722 - val_accuracy: 0.8462
Epoch 4/100
27/27 [==============================] - 0s 4ms/step - loss: 0.7013 - accuracy: 0.7641 - val_loss: 0.5485 - val_accuracy: 0.8529
Epoch 5/100
27/27 [==============================] - 0s 4ms/step - loss: 0.6271 - accuracy: 0.7822 - val_loss: 0.5003 - val_accuracy: 0.8484
Epoch 6/100
27/27 [==============================] - 0s 4ms/step - loss: 0.5938 - accuracy: 0.7905 - val_loss: 0.4712 - val_accuracy: 0.8462
Epoch 7/100
27/27 [==============================] - 0s 3ms/step - loss: 0.5664 - accuracy: 0.8026 - val_loss: 0.4560 - val_accuracy: 0.8529
Epoch 8/100


[I 2024-02-12 10:32:42,129] Trial 6 finished with value: 0.8619909286499023 and parameters: {'filters': 38, 'dropout_rate': 0.4839877280962367, 'dense_units': 116}. Best is trial 1 with value: 0.9027149081230164.


Epoch 1/100
27/27 [==============================] - 1s 9ms/step - loss: 1.0525 - accuracy: 0.6217 - val_loss: 0.9559 - val_accuracy: 0.7715
Epoch 2/100
27/27 [==============================] - 0s 4ms/step - loss: 0.8856 - accuracy: 0.7317 - val_loss: 0.6956 - val_accuracy: 0.8439
Epoch 3/100
27/27 [==============================] - 0s 4ms/step - loss: 0.6972 - accuracy: 0.7664 - val_loss: 0.5322 - val_accuracy: 0.8575
Epoch 4/100
27/27 [==============================] - 0s 4ms/step - loss: 0.6129 - accuracy: 0.7867 - val_loss: 0.4865 - val_accuracy: 0.8529
Epoch 5/100
27/27 [==============================] - 0s 4ms/step - loss: 0.5698 - accuracy: 0.7988 - val_loss: 0.4624 - val_accuracy: 0.8529
Epoch 6/100
27/27 [==============================] - 0s 4ms/step - loss: 0.5329 - accuracy: 0.8154 - val_loss: 0.4398 - val_accuracy: 0.8575
Epoch 7/100
27/27 [==============================] - 0s 4ms/step - loss: 0.5155 - accuracy: 0.8214 - val_loss: 0.4420 - val_accuracy: 0.8484
Epoch 8/100
2

[I 2024-02-12 10:32:49,834] Trial 7 finished with value: 0.8710407018661499 and parameters: {'filters': 38, 'dropout_rate': 0.41843538144886583, 'dense_units': 197}. Best is trial 1 with value: 0.9027149081230164.


Best Hyperparameters: {'filters': 52, 'dropout_rate': 0.237586017646276, 'dense_units': 191}


In [111]:
best_params

{'filters': 52, 'dropout_rate': 0.237586017646276, 'dense_units': 191}

In [114]:

import pickle

# fit and evaluate a model
def evaluate_model(trainX, trainy,validX,validy, testX, testy):
#  verbose, epochs, batch_size = 1, 1500, 100
 n_timesteps, n_features, n_outputs = trainX.shape[1], trainX.shape[2], 3
 model = Sequential()
 model.add(Conv1D(filters=best_params['filters'], kernel_size=2, activation='relu', input_shape=(n_timesteps,n_features)))
 model.add(Conv1D(filters=best_params['filters'], kernel_size=1, activation='relu'))
 model.add(Dropout(best_params['dropout_rate']))
#  model.add(MaxPooling1D(pool_size=2))
 model.add(Flatten())
 model.add(Dense(best_params['dense_units'], activation='relu'))
 model.add(Dense(n_outputs, activation='softmax')) # "softmax" for multi-class
 model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
 # fit network
 history=model.fit(trainX, trainy, validation_data=(validX, validy), epochs=epochs, batch_size=batch_size,callbacks=[callback], verbose=verbose)
 #summarize_mode
 print(model.summary())
 # evaluate model
 _, accuracy = model.evaluate(testX, testy, batch_size=batch_size, verbose=0)
 # '_,'-->a variable is being used for a specific purpose, but its value is not of interest or not used in the subsequent code.
 return accuracy,history

In [116]:
scores = list()
score,history= evaluate_model(X_train_arr, y_train_arr, X_valid_arr, y_valid_arr, X_test_arr, y_test_arr)
score = score * 100.0
scores.append(score)
# summarize results
summarize_results(scores)

Epoch 1/100
27/27 [==============================] - 1s 9ms/step - loss: 1.0463 - accuracy: 0.5750 - val_loss: 0.9302 - val_accuracy: 0.7466
Epoch 2/100
27/27 [==============================] - 0s 4ms/step - loss: 0.8469 - accuracy: 0.7430 - val_loss: 0.6518 - val_accuracy: 0.8507
Epoch 3/100
27/27 [==============================] - 0s 4ms/step - loss: 0.6288 - accuracy: 0.7882 - val_loss: 0.5001 - val_accuracy: 0.8303
Epoch 4/100
27/27 [==============================] - 0s 4ms/step - loss: 0.5343 - accuracy: 0.8184 - val_loss: 0.4727 - val_accuracy: 0.8394
Epoch 5/100
27/27 [==============================] - 0s 4ms/step - loss: 0.5027 - accuracy: 0.8131 - val_loss: 0.4548 - val_accuracy: 0.8439
Epoch 6/100
27/27 [==============================] - 0s 4ms/step - loss: 0.4839 - accuracy: 0.8244 - val_loss: 0.4404 - val_accuracy: 0.8258
Epoch 7/100
27/27 [==============================] - 0s 4ms/step - loss: 0.4757 - accuracy: 0.8214 - val_loss: 0.4362 - val_accuracy: 0.8484
Epoch 8/100
2

**Experiment**

In [ ]:

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import pickle

# fit and evaluate a model
def evaluate_model_2(trainX, trainy,validX,validy, testX, testy):
 verbose, epochs, batch_size = 1, 1, 100
 n_timesteps, n_features, n_outputs = trainX.shape[1], trainX.shape[2], 7
 model = Sequential()
 model.add(Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=(n_timesteps,n_features)))
 model.add(Conv1D(filters=64, kernel_size=3, activation='relu'))
 model.add(Dropout(0.5))
 model.add(MaxPooling1D(pool_size=2))
 model.add(Flatten())
 model.add(Dense(100, activation='relu'))
 model.add(Dense(n_outputs, activation='softmax')) # "softmax" for multi-class
 model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
 # fit network
 history=model.fit(trainX, trainy, validation_data=(validX, validy), epochs=epochs, batch_size=batch_size,callbacks=[callback], verbose=verbose)
 #summarize_mode
 print(model.summary())
 # evaluate model
 _, accuracy = model.evaluate(testX, testy, batch_size=batch_size, verbose=0)
 # '_,'-->a variable is being used for a specific purpose, but its value is not of interest or not used in the subsequent code.
 return accuracy,history